defero/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('messenger.urls')),
)

messenger/urls.py
__author__ = 'Wayne'
from django.conf.urls import patterns, url

urlpatterns = patterns('',
                       url(r'^user$', 'messenger.views.user_page'),

                       url(r'^logout$', 'messenger.views.user_logout'),
                       url(r'^login', 'messenger.views.log_in'),

                       url(r'^messages$', 'messenger.messenger_views.list_messages'),
                       url(r'^messages/$', 'messenger.messenger_views.list_messages'),
                       url(r'^messages/new$', 'messenger.messenger_views.new_message'),
                       url(r'^messages/(?P<uuid>.*)/reply$', 'messenger.messenger_views.reply'),
                       url(r'^messages/(?P<uuid>.*)/$', 'messenger.messenger_views.read_message'),


                       url(r'^tos$', 'messenger.messenger_static_pages.privacy'),
                       url(r'^about$', 'messenger.messenger_static_pages.about'),

                       # Everything else will match home.
                       url(r'^', 'messenger.views.home'),

                       )

messenger/models.py
from django.db import models
from django.contrib.auth import get_user_model


class Officer(models.Model):
    """
    We are not extending User for Officer
    """
    user = models.OneToOneField(get_user_model())
    role = models.CharField(max_length=100)

    def __str__(self):
        return self.role


class BaseMessage(models.Model):
    """
    All messages are anonymous unless they are written by an officer
    """
    content = models.TextField()

    time_posted = models.DateTimeField()
    conversation_id = models.CharField(max_length=40, blank=True)

    author = models.ForeignKey(Officer, blank=True, null=True)


class Conversation(models.Model):
    """
    Conversations are identified by a unique UUID. All messages are associated with a conversation.
    Messages have sequential IDs as they are never exposed to the user.
    """
    uuid = models.CharField(max_length=40) # UUID length is max 16 chars

    recipients = models.ManyToManyField(get_user_model(), related_name='recipient_set')  # These are people allowed to view the conversation. Cannot be changed
    messages = models.ManyToManyField(BaseMessage, related_name='message_set')  # A list of all messages belonging to this conversation.
    subject = models.CharField(max_length=200)  # A headline for the conversation, can be changed by either party

messenger/forms.py
__author__ = 'Wayne'
from django import forms
from django.contrib.auth import authenticate
from messenger.models import Officer
from django.utils.safestring import mark_safe


class LoginForm(forms.Form):
    username = forms.CharField(max_length=100, label='User ID')
    password = forms.CharField(widget=forms.PasswordInput())

    def clean(self):
        user = self.login()
        if not user or not user.is_active:
            raise forms.ValidationError('Sorry, that login was invalid. Please try again.')
        return self.cleaned_data

    def login(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        return user


class MessageForm(forms.Form):
    recipients = forms.ModelMultipleChoiceField(Officer.objects.all(),
                                                help_text='You can select more than one person.',
                                                widget=forms.CheckboxSelectMultiple)
    content = forms.CharField(widget=forms.Textarea, help_text='Be as detailed or brief as you want. '
                                                               'Messages are always anonymous.',
                              label='Message')

    password = forms.CharField(widget=forms.PasswordInput, help_text=mark_safe('This is optional, but will allow you to'
                                                                               ' continue an anonymous conversation. '
                                                                               '<a href="/about">More information</a>.'),
                               required=False)
    password_again = forms.CharField(widget=forms.PasswordInput, required=False,
                                     help_text='Type your password again to make sure you have it right.')

    def clean(self):
        cleaned_data = super(MessageForm, self).clean()
        password = cleaned_data.get('password')
        password_again = cleaned_data.get('password_again')

        if password:
            if password_again:
                if password != password_again:
                    # Only do something if both passwords do not match.
                    msg = "Passwords must match."
                    self._errors["password"] = self.error_class([msg])
                    self._errors["password_again"] = self.error_class([msg])

                    # These fields are no longer valid. Remove them from the
                    # cleaned data.
                    del cleaned_data["password"]
                    del cleaned_data["password_again"]
            else:

                # Only do something if both passwords do not match.
                msg = "Please type your password twice to ensure correctness"
                self._errors["password"] = self.error_class([msg])
                self._errors["password_again"] = self.error_class([msg])

                # These fields are no longer valid. Remove them from the
                # cleaned data.
                del cleaned_data["password"]
                del cleaned_data["password_again"]

        return cleaned_data


class ReplyForm(forms.Form):
    content = forms.CharField(widget=forms.Textarea, help_text='Reply to this conversation. People who can view this '
                                                               'conversation will be able to see your message.',
                              label='Message')

messenger/views.py
from django.shortcuts import render_to_response, HttpResponseRedirect, render, RequestContext
from messenger.forms import LoginForm, MessageForm
from django.views.decorators.cache import never_cache, cache_control
from django.contrib.auth import logout
from django.contrib.auth import login


@never_cache
@cache_control(no_cache=True, must_revalidate=True, max_age=0, no_store=True)
def home(request, output=None):
    if not output:
        output = dict()
    output['title'] = "Write a message"
    if 'login_form' not in output:
        output['login_form'] = LoginForm()
    if 'message_form' not in output:
        output['message_form'] = MessageForm()
    return render_to_response('front_page.html', output, context_instance=RequestContext(request))


@never_cache
@cache_control(no_cache=True, must_revalidate=True, max_age=0, no_store=True)
def log_in(request):
    if request.user.is_authenticated():
        # prevent logged in users from logging in again?
        return HttpResponseRedirect("/")

    if request.method == 'POST':  # If the form has been submitted...
        form = LoginForm(request.POST)  # A form bound to the POST data
        if request.POST and form.is_valid():
            user = form.login()
            if user:
                login(request, user)
                output = dict()
                output['success_message'] = "You are now logged in. Remember to log out when you are finished."
                return HttpResponseRedirect("/messages/")
            else:
                return render(request, 'user_login.html', {'login_form': form}, context_instance=RequestContext(request))
        else:
            return render(request, 'user_login.html', {'login_form': form}, context_instance=RequestContext(request))

    else:
        return render(request, 'user_login.html', {'login_form': LoginForm()}, context_instance=RequestContext(request))


@never_cache
@cache_control(no_cache=True, must_revalidate=True, max_age=0, no_store=True)
def user_page(request):
    """
    We aggressively prevent caching to avoid another user on the computer viewing a cached page that
    displays a private message.
    """
    if request.user.is_authenticated():
        output = dict()
        output['success_message'] = "You are now logged in. Remember to log out when you are finished."
        return home(request, output)
    else:
        return HttpResponseRedirect("/user/login")


@never_cache
@cache_control(no_cache=True, must_revalidate=True, max_age=0, no_store=True)
def user_logout(request):
    """
    Simple logout functionality.
    """
    logout(request)

    output = dict()
    output['success_message'] = "You have been successfully logged out."
    return home(request, output)

templates/about.html
{% extends 'base.html' %}

{% block page_title %}About{% endblock %}

{% block content %}

    <a class="back_link" href="/">« Back to home</a>

    <h1>About Messenger</h1>
    <p>Messenger was created as a result of the feedback gathered by the college leadership team by residents.</p>

    <h2>What is it for?</h2>
    <p>The aim of Messenger is to allow anyone to communicate with an officer anonymously. Examples of why this might
    be needed:
    </p>
    <ul>
        <li>There is an embarrassing problem and advice is needed</li>
        <li>Reporting potential assaults in college, where the person in question may be friend or family.</li>
        <li>An issue involving an officer or staff in college</li>
    </ul>
    <p>Messenger can facilitate anonymous conversations with an officer, which improves on a simple one-way report.</p>

    <h2>How does it work?</h2>
    <p>Anyone can send an anonymous message and choose who to send it to.</p>
    <p>If they choose to, they can enter a password so they can continue the 'conversation' with the officer(s) online.
    This process simply assigns a random user id number to the user, which they can use to log in and check for new
    messages.</p>
    <p>Officers will check their messages regularly and reply to them as soon as they can.</p>

    <h2>How secure is this?</h2>
    <p>Messages are not stored on your computer and are not associated with any personally identifiable information.
    Messenger strives to be truly anonymous and there is no way, short of identifying yourself in the message, for the
    officer to identify the author.</p>
    <p>The website also uses secure technology such as HTTPS encryption and not caching data to ensure that malicious
    people cannot eavesdrop on your connection to the website.</p>

    <h2>Who made this?</h2>
    <p>A former resident of Burgmann College, Wayne Tsai. You can view the open-source code for the website here:
    <a href="https://github.com/watbe/defero">Github</a>. He is also the person you should email if there are any
    problems using this website.</p>

    <a class="back_link" href="/">« Back to home</a>

{% endblock %}

templates/base.html
{% extends 'foundation/base.html' %}

{% block css %}
    <link rel="stylesheet" href="{{ STATIC_URL }}defero.css"/>
    <link href="{{ STATIC_URL }}favicon.ico" rel="icon" type="image/x-icon"/>
{% endblock %}

{% block head_js %}
    <script type="text/javascript" src="//use.typekit.net/obk5zhn.js"></script>
    <script type="text/javascript">try{Typekit.load();}catch(e){}</script>
    <script type="text/javascript" src="/static/jquery-1.11.min.js"></script>
    <script type="text/javascript">
    $( document ).ready(function() {
        $("ul#id_recipients input").each(function() {
            $(this).hide();

            var $image = $("<img src='/static/check_off.png' />").insertAfter(this);

            if($(this).is(":checked")) {
                $image.attr("src", "/static/check_on.png");
                $(this).prop('checked', true);
                $(this).parent().parent().addClass("checked");
            }

            $(this).parent().parent().click(function() {
                var $checkbox = $(this).children("label").children("input");
                if($checkbox.is(':checked')) {
                    $image.attr("src", "/static/check_off.png");
                    $checkbox.prop('checked', false)
                    $(this).removeClass("checked");
                } else {
                    $image.attr("src", "/static/check_on.png");
                    $checkbox.prop('checked', true)
                    $(this).addClass("checked");
                }
            })
        });
    });
    </script>
{% endblock %}

{% block title %}{% block page_title %}{{ title }}{% endblock %} | Messenger{% endblock %}


{% block base_body %}
{#    <nav class="top-bar" data-topbar>#}
{#        <ul class="title-area">#}
{#            <li class="name"><h1><a href="/">Messenger</a></h1></li>#}
{#            <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>#}
{#        </ul>#}
{#        <section class="top-bar-section"> <!-- Right Nav Section -->#}
{#            <ul class="right">#}
{#                {% if user.is_authenticated %}#}
{#                    <li><a href="/messages/">Messages</a></li>#}
{#                    <li class="active"><a href="/logout">Logout</a></li>#}
{#                {% else %}#}
{#                    <li class="active"><a href="/user/login">Log In</a></li>#}
{#                {% endif %}#}
{#            </ul>#}
{#        </section>#}
{#    </nav>#}

    <header class="row content_wrapper">
        <a id="site_title" href="/">Messenger</a>
        {% if not user.is_authenticated %}
            <a class="button right login" href="/login">Login</a>
        {% else %}
            <a class="button right logout" href="/logout">Logout</a>
            <a class="button right login" href="/messages">View messages</a>
        {% endif %}
    </header>

    <div class="row content_wrapper">
        {% if success_message %}
            <div data-alert class="alert-box success radius">
                {{ success_message }}
                <a href="#" class="close">&times;</a>
            </div>
        {% endif %}

        <div class="row">

{#            <div class="medium-2 columns">#}
{##}
{#                <p class="page_help">#}
{#                    {% block description %}#}
{#                        {{ description }}#}
{#                    {% endblock %}#}
{#                </p>#}
{##}
{#                <h3>Site links</h3>#}
{#                <ul class="side-nav">#}
{#                    <li><a href="/faq">Frequently asked questions</a></li>#}
{#                    <li><a href="/privacy">Privacy Policy</a></li>#}
{#                </ul>#}
{#                <h3>External Links</h3>#}
{#                <ul class="side-nav">#}
{#                    <li><a href="http://crcc.org.au/">Canberra Rape Crisis Centre</a></li>#}
{#                    <li>CRCC Phone: 02 6247 2525</li>#}
{#                    <li>ANU Security: 02 612 52249</li>#}
{#                </ul>#}
{##}
{#            </div>#}

            <div class="medium-12 columns">

                {% block content %}
                    {{ content }}
                {% endblock %}

            </div>

{#            <div class="medium-2 columns">#}
{##}
{#            </div>#}
        </div>
    </div>

    <footer class="row content_wrapper">
        <nav class="footer">
            <a href="/about">What is Messenger?</a>
            <a href="/tos">Privacy, Security and Terms of Service</a>
        </nav>
    </footer>
{% endblock %}

templates/front_page.html
{% extends 'base.html' %}

{% block page_title %}Send a message{% endblock %}

{% block description %}
Messenger is a website that helps facilitate the anonymous reporting of sexual harassment and assault that may have
occurred. It provides anonymous two-way communication if needed.
{% endblock %}

{% block content %}

    {{ content }}

    <p>Messenger is a website to help you communicate <strong>anonymously</strong> with a Burgmann Officer.
       <br/> Read about <a href="/about">what it is and how to use it</a>.</p>

    <div id="message_form">
        {% if message_form.non_field_errors %}
            <div data-alert class="alert-box warning radius">
                {% for error in message_form.non_field_errors %}
                    <span>{{ error }}</span>
                {% endfor %}
                <a href="#" class="close">&times;</a>
            </div>
        {% endif %}
        {# We ensure that autocomplete is forced off to prevent browsers from saving messages #}
        <form action="/messages/new" method="post" autocomplete="off">{% csrf_token %}

            <div class="field_wrapper">

                <label for="id_content">Begin with a message</label>
                {% if message_form.content.help_text %}
                    <small class="description">{{ message_form.content.help_text }}</small>
                {% endif %}

                {{ message_form.content }}

                {% if message_form.content.errors %}
                    {% for error in message_form.content.errors %}
                        <small class="error">{{ error|escape }}</small>
                    {% endfor %}
                {% endif %}

            </div>

            <div class="field_wrapper">

                <label for="id_recipients">Choose the recipients of this message</label>
                {% if message_form.recipients.help_text %}
                    <small class="description">{{ message_form.recipients.help_text }}</small>
                {% endif %}

                {{ message_form.recipients }}

                <div class="clearfix"></div>

                {% if message_form.recipients.errors %}
                    {% for error in message_form.recipients.errors %}
                        <small class="error">{{ error|escape }}</small>
                    {% endfor %}
                {% endif %}

            </div>

            <div class="field_wrapper">
                {% if not user.is_authenticated %}
                            <label>Do you want to be able to view and send replies?</label>
                            {% if message_form.password.help_text %}
                                <small class="description">{{ message_form.password.help_text }}</small>
                            {% endif %}
                            <div class="medium-4 columns">
                                <label for="id_content" class="small">Password</label>
                                {{ message_form.password }}

                                {% if message_form.password.errors %}
                                    {% for error in message_form.password.errors %}
                                        <small class="error">{{ error|escape }}</small>
                                    {% endfor %}
                                {% endif %}
                            </div>

                            <div class="medium-4 columns">
                                <label for="id_content" class="small">Password again</label>
                                {{ message_form.password_again }}

                                {% if message_form.password_again.errors %}
                                    {% for error in message_form.password_again.errors %}
                                        <small class="error">{{ error|escape }}</small>
                                    {% endfor %}
                                {% endif %}
                            </div>
                            <div class="clearfix"></div>
                {% else %}
                    <label>You will be able to view and send replies</label>
                    <p><strong>You are currently logged in as user: {{ user.username }}.</strong> This message will be automatically
                        added to the list of conversations you can access so you do not have to create a new account.
                    </p>
                    <p>Your message will still be completely anonymous, however, you may choose to <a href="/logout">log out</a> and
                    create a new account.</p>
                {% endif %}
            </div>

            <div class="field_wrapper send_message">
                <label>Review and send</label>
                    <small class="description">Be sure to double-check your message and who you are sending it to.</small>
                <p>
                    <button type="submit">Send message</button>
                </p>
                <p>
                    <small class="description">By clicking this button,
                        you agree to the <a href="/tos" target="_blank">terms and conditions</a> for this service.</small>
                </p>
            </div>

        </form>
    </div>

{% endblock %}

templates/logged_out.html
{% extends 'base.html' %}

{% block page_title %}Logged out{% endblock %}

{% block content %}
    You have been successfully logged out. <a href="/">Return to the front page</a>.
{% endblock %}

templates/message_conversation.html
{% extends 'base.html' %}

{% block page_title %}Conversation{% endblock %}

{% block description %}
    This is where you can view and send replies to receipients of this conversation. Remember that <strong>all messages are
    anonymous</strong> regardless if you are logged in or not. You can identify yourself in replies at your own
    discretion.
{% endblock %}

{% block content %}

    <h2>Conversation</h2>
    <div class="conversation_id panel callout radius">
        Conversation ID: {{ conversation.uuid }}<br/><br/>
        Users that can can view this conversation: {{ authorised_users|join:", "  }}
    </div>

    {% for message in conversation.messages.all %}
        <div class="message radius panel {% if message.author %}officer_message{% endif %}">
        <p>{{ message.content }}</p>
        <span class="author">
            {% if message.author %}
                Message written by {{ message.author }} at {{ message.time_posted }}
            {% else %}
                Message written by Anonymous User at {{ message.time_posted }}
            {% endif %}
        </span>
        </div>


    {% endfor %}

    <div id="message_form">
        <h3>Reply</h3>
        {% if reply_form.non_field_errors %}
            <div data-alert class="alert-box warning radius">
                {% for error in reply_form.non_field_errors %}
                    <span>{{ error }}</span>
                {% endfor %}
                <a href="#" class="close">&times;</a>
            </div>
        {% endif %}
        {# We ensure that autocomplete is forced off to prevent browsers from saving messages #}
        <form action="reply" method="post" autocomplete="off">{% csrf_token %}
            {% for field in reply_form %}
                <div class="input {{ field.field.widget.attrs.class }}">
                    {{ field.label_tag }}
                    {{ field }}
                    {% if field.errors %}
                        {% for error in field.errors %}
                            <small class="error">{{ error|escape }}</small>
                        {% endfor %}
                    {% endif %}
                    {% if field.help_text %}
                        <small class="description">{{ field.help_text }}</small>
                    {% endif %}
                </div>
            {% endfor %}

            {% if officer %}
                <p><strong>You are sending this reply as {{ officer.role }}.</strong></p>
            {% endif %}

            {% if anonymous %}
                <p><strong>You are sending this reply as Anonymous User.</strong></p>
            {% endif %}

            <button type="submit">Send reply</button>
        </form>
    </div>

{% endblock %}

templates/message_list.html
{% extends 'base.html' %}

{% block page_title %}Your conversations{% endblock %}

{% block description %}
    This is a list of conversations that you can access. Click on a conversation to view it and create replies.
{% endblock %}

{% block content %}

    <h2>Conversations</h2>
    {% if conversation_list %}
        <p>You are part of the following conversations:</p>


        <table>
            <thead>
                <tr>
                    <th>Subject</th>
                    <th>Conversation ID</th>
                    <th>Replies</th>
                    <th>Participants</th>
                    <th>Date/time created</th>
                    <th>Last reply</th>
                </tr>
            </thead>
            <tbody>
                {% for conversation in conversation_list reversed %}
                    <tr>
                        <td>
                            {% if conversation.subject %}
                                {{ conversation.subject }}
                            {% else %}
                                No subject
                            {% endif %}
                        </td>
                        <td>
                            <a href="/messages/{{ conversation.uuid }}/">{{ conversation.uuid }}</a>
                        </td>
                        <td class="center">
                            {{ conversation.messages.count }}
                        </td>
                        <td class="center">
                            {{ conversation.recipients.count }}
                        </td>
                        <td>
                            {{ conversation.messages.all.0.time_posted }}
                        </td>
                        <td>
{#                            {% with conversation.messages.all|last as end %}#}
{#                                {{ end.time_posted }}#}
{#                            {% endwith %}#}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% endif %}


{% endblock %}

templates/message_not_found.html
{% extends 'base.html' %}

{% block page_title %}Not Found{% endblock %}

{% block content %}

    <h2>Not Found</h2>
    <p>The URL you are looking either does not exist or you do not have permission to view it.</p>

{% endblock %}

templates/message_success.html
{% extends 'base.html' %}

{% block page_title %}Message sent{% endblock %}

{% block description %}
    Your message has been sent to the chosen officer(s). If you choose to be anonymous, you will not be able to view
    the message or send a reply.
{% endblock %}

{% block content %}

    <h2>Message sent</h2>
    <div class="conversation_id panel callout radius">
        <p>Message ID: {{ conversation.uuid }}</p>
        <p>You may wish to take note of this ID for future purposes. This ID will prove that you wrote this message.</p>
    </div>

    <p>Thank you for sending a message to our officers. Officers will endeavour to read your message as soon as
        possible but please be aware that due to the anonymous nature of this service, follow up options may be limited.
    </p>
    <p>If you wish to speak to someone, there are confidential services available on campus such as
        <a href="http://counselling.anu.edu.au/">ANU Counselling</a>. If anyone's life is in danger, you need to let
        someone know <strong>immediately</strong>.</p>

    <hr/>

    {% if new_user %}

        <p>Since you entered a password into the field, a new account has been created for you. You can now log in with
        the following details and access replies to the message and send further messages. </p>
        <p>This user ID and password will not be shown again, so make note of it now.</p>
        <div class="panel">
            <p><strong>User ID</strong>: {{ new_user }}<br/>
            <strong>Password</strong>: The one you entered when you submitted this form.</p>
        </div>
        <p>Note that the password is encrypted and cannot be retrieved under any circumstances. After you log in, there are
        options to change your password and add an email address if you wish to be notified about new replies. </p>

    {% elif user.is_anonymous %}

        <p>Your message has been sent to the recipient(s) that you selected. As you did not enter a password, you will not
            be able to view replies or communicate further with the officer. </p>
        <p>You may want to keep the message ID safe if you wish to identify yourself as the author of the message in the
            future, otherwise the message will remain <completely></completely> anonymous. </p>

    {% elif logged_in %}

        <p>Your message has been sent and associated with your current user account. You can view replies and continue
            communications by viewing your list of conversations.</p>

    {% endif %}



{% endblock %}

templates/user_logged_out.html
{% extends 'base.html' %}

{% block page_title %}Logged out{% endblock %}

{% block content %}
    You have been successfully logged out. <a href="/">Return to the front page</a>.
{% endblock %}

templates/user_login.html
{% extends 'base.html' %}

{% block title %}Log in to Messenger{% endblock %}

{% block description %}
    After logging in, you can view messages that you have sent and replies that you have received.
{% endblock %}

{% block content %}

    <div class="small_form">

        <h2>Login</h2>
        <p>Log in to view your messages.</p>

        <div id="login">

            {% if login_form.non_field_errors %}
                <div data-alert class="alert-box warning radius">
                    {% for error in login_form.non_field_errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                    <a href="#" class="close">&times;</a>
                </div>
            {% endif %}

            {# We ensure that autocomplete is forced off to prevent browsers from saving passwords and usernames #}
            <form action="/login" method="post" autocomplete="off">{% csrf_token %}
                {% for field in login_form %}
                    <div class="input {{ field.field.widget.attrs.class }}">
                        {{ field.label_tag }}
                        {{ field }}
                        {% if field.errors %}
                            {% for error in field.errors %}
                                <small class="error">{{ error|escape }}</small>
                            {% endfor %}
                        {% endif %}
                    </div>
                {% endfor %}
                <input type="submit" class="input" value="Login"/>
            </form>
        </div>
    </div>

{% endblock %}